global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Snowflake LangChain Agent
  - job_name: 'snowflake-agent'
    static_configs:
      - targets: ['snowflake-agent:8001']
    scrape_interval: 10s
    metrics_path: /metrics
    scrape_timeout: 5s

  # vLLM Service (if it exposes metrics)
  - job_name: 'vllm-service'
    static_configs:
      - targets: ['mock-vllm:8000']
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s

  # Grafana
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    scrape_interval: 30s
