services:
  # Snowflake LangChain Agent
  snowflake-agent:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: snowflake-langchain-agent
    ports:
      - "8000:8000"
    environment:
      # Snowflake Configuration
      - SNOWFLAKE_ACCOUNT=${SNOWFLAKE_ACCOUNT}
      - SNOWFLAKE_USER=${SNOWFLAKE_USER}
      - SNOWFLAKE_PASSWORD=${SNOWFLAKE_PASSWORD}
      - SNOWFLAKE_WAREHOUSE=${SNOWFLAKE_WAREHOUSE}
      - SNOWFLAKE_DATABASE=${SNOWFLAKE_DATABASE}
      - SNOWFLAKE_SCHEMA=${SNOWFLAKE_SCHEMA}
      - SNOWFLAKE_ROLE=${SNOWFLAKE_ROLE}
      
      # Gemini API Configuration
      - VLLM_BASE_URL=https://generativelanguage.googleapis.com/v1beta
      - VLLM_MODEL_NAME=gemini-2.5-flash
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - VLLM_TIMEOUT=30
      - VLLM_MAX_RETRIES=3
      
      # Auth Configuration
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-here}
      - AUTH_ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - ALLOWED_ORIGINS=http://localhost:3000,http://localhost:8000
      - ALLOWED_METHODS=GET,POST,PUT,DELETE,OPTIONS
      
      # App Configuration
      - LOG_LEVEL=INFO
      - ENVIRONMENT=development
    # No dependencies - using Gemini API
    networks:
      - snowflake_llm_network
    restart: unless-stopped

  # Using Gemini API - no local container needed

networks:
  snowflake_llm_network:
    driver: bridge
